// 正式聊天历史与索引；文案集中在此，校对不需要修改渲染器。
// 每条消息使用原有结构；date 为 YYYY-MM-DD，图片描述暂用 text。
window.chatPreviewData = [
  {
    id: "group", name: "好友群", avatar: "群", color: "group", status: "6 位成员", date: "2026-09-01", type: "group",
    nicknames: { "余晓明": "狼宝", "谢雨菲": "鹅宝", "白赋": "豹宝", "陶子欣": "鸽宝", "丁子卓": "猪宝", "我": "我" },
    messages: [
      // 平常有人接话的日常片段。
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "07:12", text: "早上吃什么" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "07:56", text: "才起", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "07:56", text: "吃牛杂粉丝汤", self: true },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "07:56", text: "吃了俩肉包俩菜包俩烧麦，好饱" },
      { type: "image", sender: "我", avatar: "我", date: "2026-09-01", time: "07:56", src: "asset/memes/pig_eating.jpg", alt: "猪吃饭", mediaKind: "meme", width: 1080, height: 1092, self: true },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "08:12", text: "不吃早饭" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "08:12", text: "不吃早饭" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "08:12", text: "不吃早饭" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "08:54", text: "好崩溃" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "08:54", text: "一大早就不想活了" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "08:54", text: "甲方说海报图要高级，要留白" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "08:55", text: "接着又给我发了个文档" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "08:55", text: "里面有他妈两整页文案？？？" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "08:55", text: "何意味" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "08:55", text: "何意味" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "08:55", text: "逗宝逗宝帮我把两页文案总结成三个字" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "08:56", text: "从文档里随便挑一句拉倒" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "08:56", text: "感觉对面的脑子留白倒是挺多的" },
      { type: "image", sender: "我", avatar: "我", date: "2026-09-01", time: "08:56", src: "asset/memes/zero_brain_cat.jpg", alt: "含有百分之零大脑", mediaKind: "meme", width: 1084, height: 906, self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "08:56", text: "甲方Belike⬆️", self: true },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "08:57", text: "没这么可爱" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "08:57", text: "没这么可爱" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "08:57", text: "没这么可爱" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "08:57", text: "没这么可爱", self: true },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "09:26", text: "轮到我崩溃了" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "09:26", text: "十万年前问交通局的邮件终于回复了" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "09:26", text: "结果发现这信息加上，好多东西都要改" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "09:26", text: "本来稿子都打算发给编辑了" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "09:27", text: "v2.0更新内容：全部重做" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "09:27", text: "我那么大一个稿子呢.jpg", self: true },
      { type: "text", sender: "陶子欣", avatar: "陶", date: "2026-09-01", time: "09:28", text: "作为编辑，我要说，要是我约稿的作者能有你一半严谨就好了。" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "09:28", text: "没办法，交通事故这种报道可不敢乱写" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "09:28", text: "职业道德这一块儿", self: true },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "10:38", text: "好困" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "10:38", text: "好困" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "10:38", text: "好困" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "11:04", text: "有人在图书馆小便池里拉屎" },
      { type: "image", sender: "我", avatar: "我", date: "2026-09-01", time: "11:04", src: "asset/memes/shit.png", alt: "屎", mediaKind: "meme", width: 456, height: 329, self: true },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "11:04", text: "？" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "11:05", text: "？" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "11:05", text: "？" },
      { type: "text", sender: "陶子欣", avatar: "陶", date: "2026-09-01", time: "11:25", text: "？" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "11:37", text: "午饭吃什么" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "11:38", text: "可以不要报道完厕所然后问吃什么吗" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "11:49", text: "点个咖喱猪排蛋包饭" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "11:49", text: "想吃泰式绿咖喱" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "11:49", text: "高级的嘞" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "11:49", text: "大楼食堂启动" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "11:49", text: "有时候食堂也有鸡肉咖喱盖浇饭" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "11:50", text: "森罗启动" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "11:50", text: "我要关东煮吃到饱" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "11:50", text: "它家新的番茄鸡蛋牛肉便当好吃" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "11:51", text: "下次试试" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "11:51", text: "搞得我也想点关东煮了", self: true },
      { type: "image", sender: "陶子欣", avatar: "陶", date: "2026-09-01", time: "12:11", src: "asset/images/tzx_bento.png", alt: "陶子欣的便当", width: 1086, height: 1448},
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "12:12", text: "真不错" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "12:12", text: "真不错", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "12:12", text: "其实我最后还是自己做了", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "12:12", text: "冰箱里的玉米再不吃要发霉了", self: true },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "12:13", text: "自由职业就是爽啊" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "14:48", text: "让每一次购物，都遇上刚刚好的价格。" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "14:48", text: "这句话有毛病吗 @黄油蛛丝 @来财来" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "14:49", text: "我觉得没毛病" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "14:49", text: "看看编辑大人怎么说" },
      { type: "text", sender: "陶子欣", avatar: "陶", date: "2026-09-01", time: "14:56", text: "没有语病，不过你不是说甲方要留白吗？" },
      { type: "text", sender: "陶子欣", avatar: "陶", date: "2026-09-01", time: "14:56", text: "可以改成：让每一次心动，都遇上好价。" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "14:57", text: "牛逼，顺多了" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "14:57", text: "字还少了" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "14:58", text: "那必须的，编辑最爱删字了" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "14:59", text: "比如某人三小时的采访最后全被删了" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "15:00", text: "唉，不讲不讲" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "16:23", text: "我要笑死了" },
      { type: "image", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "16:23", src: "asset/images/church_door_bug.png", alt: "出了bug的教堂门", width: 1111, height: 914},
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "16:24", text: "求笑点", self: true },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "16:24", text: "就我们最近那个游戏项目" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "16:24", text: "场景那边找了半天参考做的教堂门" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "16:24", text: "高画质看着可牛逼了，各种浮雕花纹" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "16:24", text: "结果低画质走到某个角度一看" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "16:24", text: "直接穿模" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "16:24", text: "教堂里面看得一干二净" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "16:25", text: "门直接消失了？" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "16:25", text: "不是，门还在的" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "16:25", text: "估计是低画质的LOD删到什么东西了" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "16:25", text: "我猜这块儿是那个关系户负责的……" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "16:26", text: "关系户啊，这就不奇怪了，这就不奇怪了" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "16:26", text: "再让我听到……" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "16:27", text: "上帝关上了一扇门", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "16:27", text: "必然会让门可以穿模", self: true },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "16:27", text: "笑不活了" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "17:30", text: "下班" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "17:30", text: "不许" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "17:30", text: "晚上吃什么" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "17:31", text: "点份双层芝士牛肉汉堡", self: true },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "17:31", text: "好想下班" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "17:31", text: "好想下班" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "17:31", text: "好想下班" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "18:00", text: "下班" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "18:00", text: "不许" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "18:01", text: "没招了" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "18:01", text: "傻逼甲方又有新要求" },
      { type: "text", sender: "余晓明", avatar: "余", date: "2026-09-01", time: "18:01", text: "感觉今晚依旧美美加班" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "18:02", text: "太惨了" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "18:47", text: "我也溜了" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "18:47", text: "明天还得去一个小区采访" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "18:47", text: "据说那里有过命案，还是情杀" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "18:47", text: "但问了几个人，连原本的房主是男是女都对不上" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "18:48", text: "都命案了，查不到以前的报道吗", self: true },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "18:48", text: "至少网上没查到" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "18:48", text: "主要我也不是去调查这个的" },
      { type: "text", sender: "白赋", avatar: "白", date: "2026-09-01", time: "18:48", text: "就当个八卦听听" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "18:49", text: "说不定市图书馆里有什么老报纸能查到呢 @好想吃大餐" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "18:50", text: "那你要问地方文献部，我不负责这个" },
      { type: "text", sender: "陶子欣", avatar: "陶", date: "2026-09-01", time: "19:24", text: "[长文字分享：一位新兴作家的短篇小说]" },
      { type: "text", sender: "陶子欣", avatar: "陶", date: "2026-09-01", time: "19:25", text: "你们有空可以看看，写得挺不错的。" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "19:42", text: "挺好的" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "19:56", text: "好意识流" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "20:01", text: "@我 @Limit Break 上不上号" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "20:01", text: "倒杯水就来", self: true },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "20:01", text: "你昨天倒水倒了十五分钟" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "20:02", text: "这次一定", self: true },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "20:02", text: "我先开房了，速来" },
      { type: "system", sender: null, date: "2026-09-01", time: "20:02", text: "已发起语音通话" },
      { type: "system", sender: null, date: "2026-09-01", time: "22:33", text: "已结束语音通话" },
      { type: "image", sender: "我", avatar: "我", date: "2026-09-01", time: "22:34", src: "asset/memes/inhale.jpg", alt: "倒吸凉气者", mediaKind: "meme", width: 504, height: 438, self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "22:34", text: "我的金条……", self: true },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "22:35", text: "差一个房间就带出来了" },
      { type: "text", sender: "谢雨菲", avatar: "谢", date: "2026-09-01", time: "22:36", text: "玩动物损友会去了" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "23:18", text: "饿了" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "23:18", text: "去碎瓦巷觅食" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "23:19", text: "这个点还要出去吗，哈基猪你这家伙……", self: true },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "23:19", text: "夜宵要出去吃才对味" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "23:19", text: "就牧野炉屋吧", calibrationTarget: "牧野炉屋", calibrationAnswer: "炭野小院" }, //正确答案，待校准部分“牧野炉屋”，实际应为“炭野小院”
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "23:27", text: "出发" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "11:14", text: "好安静啊", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "11:14", text: "群里也没有人", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "11:14", text: "一定是把战力都调去公司了吧", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "12:04", text: "午饭吃啥", self: true },
      { type: "image", sender: "我", avatar: "我", date: "2026-09-02", time: "12:05", src: "asset/memes/cat_stare.jpg", alt: "猫咪凝视", mediaKind: "meme", width: 1078, height: 1080, self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "16:21", text: "？", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "16:21", text: "啥情况", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "16:21", text: "我也没断网啊", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "16:22", text: "@全体成员 还有活人吗", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "16:35", text: "？？？", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "16:36", text: "有人能看到我的消息吗", self: true }
    ]
  },
  {
    id: "assistant", name: "群助手", avatar: "助", color: "assistant", status: "已接入", date: "2026-07-01",
    messages: [
      { type: "text", sender: "群助手", avatar: "助", date: "2026-07-01", time: "12:30", text: "我们已经成功添加好友，开始聊天吧。" },
      { type: "text", sender: "群助手", avatar: "助", date: "2026-09-03", time: "00:01", text: "输入 /help 以查看可用命令。" }
    ]
  },
  {
    id: "ding", name: "丁子卓", avatar: "丁", color: "ding", status: "离线", date: "2026-08-09",
    messages: [
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-09", time: "18:42", text: "卧槽" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-09", time: "18:42", text: "食光仓竟然不卖烤香蕉了", calibrationTarget: "食光仓", calibrationAnswer: "炙山苑" },//正确答案，待校准部分“食光仓”，实际应为“炙山苑”
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-09", time: "18:42", text: "亏我还特别打车去星栖城" },
      { type: "text", sender: "我", avatar: "我", date: "2026-08-09", time: "18:43", text: "依旧最爱烤香蕉之人", self: true },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-09", time: "18:43", text: "不懂烤香蕉的有难了" },
      { type: "image", sender: "我", avatar: "我", date: "2026-08-09", time: "18:44", src: "asset/memes/understand.png", alt: "懂什么啊", mediaKind: "meme", width: 1473, height: 1373, self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-08-15", time: "21:55", text: "今天是网卡了吗", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-08-15", time: "21:55", text: "感觉你经常站着不动", self: true },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-15", time: "21:56", text: "不是" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-15", time: "21:56", text: "太渴了一直在喝水" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-15", time: "21:56", text: "再也不吃九格山城的炒饭了", calibrationTarget: "九格山城", calibrationAnswer: "食光仓" },//正确答案，待校准部分“九格山城”，实际应为“食光仓”
      { type: "text", sender: "我", avatar: "我", date: "2026-08-15", time: "21:57", text: "这集神了", self: true },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-15", time: "21:57", text: "咸得要死" },
      { type: "text", sender: "我", avatar: "我", date: "2026-08-15", time: "21:58", text: "不是网络害了你，是这盐害了你啊", self: true },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-28", time: "17:31", text: "炭野小院竟然开在了流明广场", calibrationTarget: "炭野小院", calibrationAnswer: "串山令" },//正确答案，待校准部分“炭野小院”，实际应为“串山令”
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-28", time: "17:31", text: "感觉烧烤和那边不太搭" },
      { type: "text", sender: "我", avatar: "我", date: "2026-08-28", time: "17:43", text: "还有店铺歧视", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-08-28", time: "17:43", text: "那今天还能上号吗", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-08-28", time: "17:43", text: "毕竟你从那边回家要挺久的", self: true },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-28", time: "17:44", text: "估计悬" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-28", time: "17:44", text: "正好今天歇一下，脖子有点疼" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-28", time: "17:45", text: "不说了" },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-28", time: "17:45", text: "我得比你们早出发" },
      { type: "image", sender: "我", avatar: "我", date: "2026-08-28", time: "23:04", src: "asset/images/ding_playing_game.png", alt: "正在游玩", width: 2160, height: 519, self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-08-28", time: "23:05", text: "不是说脖子疼吗", self: true },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-08-28", time: "23:06", text: "食疗治好了" },
      { type: "image", sender: "我", avatar: "我", date: "2026-08-28", time: "23:06", src: "asset/memes/played.png", alt: "居然敢耍俺", mediaKind: "meme", width: 1161, height: 1080, self: true },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "20:02", text: "记得更新一下游戏mod" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "20:03", text: "好", self: true },
      { type: "text", sender: "丁子卓", avatar: "丁", date: "2026-09-01", time: "20:03", text: "记得先开加速器" },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "20:04", text: "开了开了", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "20:04", text: "我已经会打那个大蜘蛛了", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-01", time: "20:04", text: "今天必带飞你们", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "08:43", text: "昨晚吃得咋样", self: true }, 
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "09:34", text: "不理我", self: true },
      { type: "image", sender: "我", avatar: "我", date: "2026-09-02", time: "09:34", src: "asset/memes/sad_seal_ball.jpg", alt: "悲伤海豹球", mediaKind: "meme", width: 1280, height: 1008, self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "10:32", text: "小哥哥不会是晕碳睡过头了吧", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "11:10", text: "怎么今天群里也没人说话", self: true },
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "12:23", text: "不是哥们", self: true }, 
      { type: "text", sender: "我", avatar: "我", date: "2026-09-02", time: "12:23", text: "你们是背着我偷偷结束乐队了吗", self: true },
      { type: "system", sender: null, date: "2026-09-02", time: "12:24", text: "已发起语音通话" },
      { type: "system", sender: null, date: "2026-09-02", time: "12:26", text: "对方未应答" },        
    ]
  }
];

window.botData = {
  members: [
    { aliases: ["猪宝", "丁子卓", "好想吃大餐"], text: "用户：好想吃大餐\n群昵称：猪宝\n最后群内活动：9月1日 23:27\n最后群消息：“出发”\n关联索引：美食" },
    { aliases: ["狼宝", "余晓明", "最初版"], text: "用户：最初版\n群昵称：狼宝\n暂无可查询索引。" },
    { aliases: ["鹅宝", "谢雨菲", "Limit Break"], text: "用户：Limit Break\n群昵称：鹅宝\n暂无可查询索引。" },
    { aliases: ["鸽宝", "陶子欣", "黄油蛛丝"], text: "用户：黄油蛛丝\n群昵称：鸽宝\n暂无可查询索引。" },
    { aliases: ["豹宝", "白赋", "来财来"], text: "用户：来财来\n群昵称：豹宝\n暂无可查询索引。" }
  ],
  // 本阶段只查询资料，不触发恢复、对白或谜题完成状态。
  indexes: [
    { aliases: ["美食"], title: "美食 · 已保存记录", summary: "用户[好想吃大餐]和美食相关的片段。", recordSetId: "food_records" },
  ]
};

// 一个 entry 是一个资料片段，数量统一按 entries.length 计算。
window.recordSets = {
  food_records: {
    title: "美食 · 已保存记录",
    entries: [
      { id: "food-01", time: "2026 年 7 月 3 日 20:25", messages: [
        { speaker: "我", time: "20:25", text: "就去炭野小院吗" },
        { speaker: "猪宝", time: "20:26", text: "嗯" },
        { speaker: "豹宝", time: "20:31", text: "谁帮我去旁边超市买瓶水饮料" },
        { speaker: "猪宝", time: "20:32", text: "你要啥" },
        { speaker: "豹宝", time: "20:32", text: "绿瓶的尖啸" },
        { speaker: "我", time: "20:33", text: "你买个红瓶的" },
        { speaker: "我", time: "20:33", text: "谁迟到谁喝" },
        { speaker: "鹅宝", time: "20:34", text: "草" },
      ] },
      { id: "food-02", time: "2026 年 7 月 10 日 19:30", messages: [
        { speaker: "豹宝", time: "19:30", text: "流明广场有啥精致点的店啊" },
        { speaker: "猪宝", time: "19:31", text: "山海膳堂" },
        { speaker: "猪宝", time: "19:31", text: "去年拿了迷其林一星的" },
        { speaker: "鹅宝", time: "19:32", text: "有点太精致了吧" },
        { speaker: "猪宝", time: "19:33", text: "其实还好" },
        { speaker: "猪宝", time: "19:33", text: "推荐鳝丝炒饭" },
      ] },
      { id: "food-03", time: "2026 年 7 月 19 日 21:43", messages: [
        { speaker: "鹅宝", time: "21:43", text: "KTV耍起" },
        { speaker: "我", time: "21:43", text: "耍完直接在碎瓦巷吃个夜宵" },
        { speaker: "我", time: "21:44", text: "多是一件美事啊" },
        { speaker: "猪宝", time: "21:44", text: "那去牧野炉屋" },
        { speaker: "鹅宝", time: "21:45", text: "猪宝严选来了" },
      ] },
      { id: "food-04", time: "2026 年 7 月 28 日 18:24", messages: [
        { speaker: "我", time: "18:24", text: "不打算吃烧烤的话" },
        { speaker: "我", time: "18:25", text: "要不就去九格山城吧" },
        { speaker: "我", time: "19:42", text: "或者牧野炉屋也行" },
        { speaker: "猪宝", time: "19:43", text: "反正中间就隔了家奶茶" },
        { speaker: "鹅宝", time: "21:45", text: "那就先集合" },
        { speaker: "鹅宝", time: "21:45", text: "到了再看哪家不用排队或者人少点" },
        { speaker: "豹宝", time: "21:45", text: "我觉得可以" },
      ] },
      { id: "food-05", time: "2026 年 8 月 1 日 19:45", messages: [
        { speaker: "我", time: "19:45", text: "那怎么说" },
        { speaker: "我", time: "19:46", text: "炙山苑约不约" },
        { speaker: "鸽宝", time: "19:51", text: "可以去食光仓吗？" },
        { speaker: "鹅宝", time: "19:51", text: "居然是鸽宝" },
        { speaker: "鹅宝", time: "19:42", text: "那这家店在哪" },
        { speaker: "鸽宝", time: "19:51", text: "就在炙山苑旁边的，不用改地点。" },
        { speaker: "我", time: "19:51", text: "那我没意见" },
        { speaker: "猪宝", time: "19:45", text: "我都行" },
      ] },
      { id: "food-06", time: "2026 年 8 月 7 日 20:07", messages: [
        { speaker: "猪宝", time: "20:07", text: "食光仓的烤香蕉神了" },
        { speaker: "猪宝", time: "20:07", text: "还能自己加炼乳或者焦糖" },
        { speaker: "我", time: "20:08", text: "听起来好诡异" },
        { speaker: "猪宝", time: "20:08", text: "没品" },
        { speaker: "鹅宝", time: "20:09", text: "和牧野炉屋的烤香蕉比呢" },
        { speaker: "猪宝", time: "20:10", text: "都好吃" },
        { speaker: "猪宝", time: "20:10", text: "炙山苑的也好吃" },
        { speaker: "我", time: "20:11", text: "烤香蕉全肯定bot来了" },
      ] },
      { id: "food-07", time: "2026 年 8 月 10 日 13:11", messages: [
        { speaker: "我", time: "13:11", text: "笑死" },
        { speaker: "我", time: "13:11", text: "不只碎瓦巷那家" },
        { speaker: "我", time: "13:11", text: "三家里面两家都不卖烤香蕉了" },
        { speaker: "猪宝", time: "13:12", text: "没品" },
        { speaker: "我", time: "13:13", text: "一看就是根本没人点所以下架了" },
        { speaker: "猪宝", time: "13:13", text: "没品！！！" },
        { speaker: "鹅宝", time: "13:13", text: "蕉之爱，同予者何人" },
      ] },
      { id: "food-08", time: "2026 年 8 月 13 日 18:12", messages: [
        { speaker: "豹宝", time: "18:12", text: "又想吃山海膳堂的鳝丝炒饭了" },
        { speaker: "我", time: "18:12", text: "饭里掺东西了" },
        { speaker: "我", time: "18:12", text: "吃完就念念不忘" },
        { speaker: "鹅宝", time: "18:12", text: "猪宝严选依旧权威" },
        { speaker: "鹅宝", time: "18:12", text: "但流明广场昨天就不给进了" },
        { speaker: "鹅宝", time: "18:12", text: "好像是临时施工之类的" },
        { speaker: "鹅宝", time: "18:12", text: "关到20号" },
        { speaker: "豹宝", time: "18:12", text: "卧槽" },
        { speaker: "豹宝", time: "18:12", text: "我的鳝丝炒饭……还给我……" },
        { speaker: "我", time: "18:12", text: "开始戒断反应了" },
      ] },
      { id: "food-09", time: "2026 年 8 月 16 日 16:28", messages: [
        { speaker: "鹅宝", time: "16:28", text: "它家不是没有烤香蕉了吗" },
        { speaker: "我", time: "16:29", text: "无所谓" },
        { speaker: "我", time: "16:29", text: "猪宝又不来" },
        { speaker: "鹅宝", time: "16:30", text: "确实" },
        { speaker: "鹅宝", time: "16:30", text: "还正好不在碎瓦巷" },
        { speaker: "豹宝", time: "16:31", text: "但它家是不是也没有炒饭" },
        { speaker: "我", time: "16:31", text: "好像真是" },
        { speaker: "我", time: "16:31", text: "忘了还有个炒饭爱好者要来" },
      ] },
      { id: "food-10", time: "2026 年 8 月 28 日 19:39", messages: [
        { speaker: "猪宝", time: "17:39", text: "流明广场新开了家烧烤" },
        { speaker: "猪宝", time: "17:39", text: "今天开业酬宾全场五折" },
        { speaker: "我", time: "17:41", text: "查了一下小众评点" },
        { speaker: "我", time: "17:41", text: "五折之后还可以用代金券" },
        { speaker: "我", time: "17:41", text: "这下不得不去了" },
        { speaker: "豹宝", time: "17:42", text: "这下不得不去了" },
        { speaker: "鹅宝", time: "17:42", text: "这下不得不去了" },
        { speaker: "鸽宝", time: "17:56", text: "我晚点也能来~" },
      ] },
      { id: "food-11", time: "2026 年 8 月 30 日 12:14", messages: [
        { speaker: "鹅宝", time: "12:14", text: "只有烧烤才开到凌晨吧" },
        { speaker: "鹅宝", time: "12:14", text: "别的顶多开到晚上十点半" },
        { speaker: "我", time: "12:15", text: "好吧" },
        { speaker: "我", time: "12:15", text: "所以我们讨论出了几个地点？" },
        { speaker: "猪宝", time: "12:16", text: "我看下" },
        { speaker: "猪宝", time: "12:20", text: "一共七家店" },
        { speaker: "猪宝", time: "12:21", text: "碎瓦巷三家，流明广场两家，星栖城两家" },
        { speaker: "鹅宝", time: "12:21", text: "星栖城是不是没有烧烤" },
        { speaker: "猪宝", time: "12:21", text: "嗯" },
        { speaker: "猪宝", time: "12:22", text: "只有碎瓦巷和流明广场各有一家" },
        { speaker: "豹宝", time: "12:26", text: "那除了山海膳堂" },
        { speaker: "豹宝", time: "12:26", text: "还有有炒饭的吗" },
        { speaker: "鹅宝", time: "12:27", text: "查查线上菜单" },
        { speaker: "猪宝", time: "12:27", text: "就山海膳堂和食光仓有" },
        { speaker: "鹅宝", time: "12:28", text: "你不会把这几家菜单都记住了吧" },
        { speaker: "猪宝", time: "12:28", text: "差不多" },
        { speaker: "豹宝", time: "12:28", text: "图书馆的记性就是好" },
        { speaker: "我", time: "12:29", text: "感觉和图书馆并没有关系……" },
      ] },
      { id: "food-12", time: "2026 年 8 月 31 日 19:21", messages: [
        { speaker: "豹宝", time: "19:21", text: "原来串山令和山海膳堂就靠在一起" },
        { speaker: "豹宝", time: "19:21", text: "上次去都没发现" },
        { speaker: "猪宝", time: "19:22", text: "有人又去吃鳝丝炒饭了" },
        { speaker: "豹宝", time: "19:22", text: "这都被你猜到了" },
      ] },
    ]
  },
};
